spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=PostgreSQL
    username: test
    password: test
  jpa:
    hibernate:
         ddl-auto: create-drop



#spring:
#  datasource:
#   url: jdbc:postgresql://localhost/test
#   username: root
#   password: changeme
#   driverClassName: org.postgresql.Drive